### PR TITLE
fix operator pod label in stateful set

### PR DESCRIPTION
**Pull request by alecholmez**
This change fixes the operator pod labels being incorrectly generated.
Instead of pods and service accounts taking the names of "blah-0"
they are now "greymatter-operator-0" in the appropriate namespace.

Signed-off-by: Alec Holmes <alecholmez@me.com>

### CODE REVIEW

**Review by joel-epstein — DISMISSED** [review]

**Review by tilleryd — CHANGES_REQUESTED** [review]
This PR makes me think there are more things we want to remain static.

**Comment by tilleryd** [comment]
@alecholmez Please do a search for the use of `config.namespace`. I see other potential changes like https://github.com/greymatter-io/gitops-core/blob/main/k8s/outputs/operator.cue#L204-L208. I think those should also be "greymatter-operator" and not the namespace.

**Comment by alecholmez** [comment]
@tilleryd I was able to test this and it seemed to work okay. Maybe @danielpcox should weigh in here as well.

**Comment by danielpcox** [comment]
I agree with David for the specific situations he mentioned. It's not that it's _broken_ if you name things identical to the namespace, it just doesn't make sense to do so, and IMO it would be better for the operator to have a stable name. People can still override it if they want to.

**Comment by danielpcox** [comment]
The service account should also not be named after the namespace

**Comment by tilleryd** [comment]
@alecholmez There are couple more changes left in `k8s/outputs/openshift.cue`.

**Comment by alecholmez** [comment]
@tilleryd totally missed that, pushed and fixed.

**Review by tilleryd — APPROVED** [review]

**Pull request merged**
