### PR TITLE
Fix oidc filter default mixins and update submodule

### PR DESCRIPTION
**Pull request by jack-bischoff**

### CODE REVIEW

**Comment by alecholmez** [comment]
@jack-bischoff I updated the submodule in my recent PR is this still valid?

**Comment by jack-bischoff** [comment]
> @jack-bischoff I updated the submodule in my recent PR is this still valid?
@alecholmez 
Yes

**Review by dontlaugh — APPROVED** [review]

**Comment by dontlaugh** [comment]
The default change to useTLS true is a good idea. There's a small chance some test environments get broken, but we can set the value explicitly in that case.

**Review by danielpcox — APPROVED** [review]
I bothered Jack about a few things I could think of that may have gone wrong, and everything checks out. Approved!

**Pull request merged**
