### PR TITLE
move ssh_private_key to ssh-private-key

### PR DESCRIPTION
**Pull request by alecholmez**
changed expected private secret from ssh_private_key to ssh-private-key to match greymatter sync's secret requirements.

Signed-off-by: Alec Holmes <alecholmez@me.com>

### CODE REVIEW

**Comment by tilleryd** [comment]
@alecholmez This is just a filename. I wasn't aware that Kubernetes had a naming convention on external files. Can you link that reference?

**Comment by tilleryd** [comment]
Also a PR to update step 2 in https://docs.greymatter.io/getting-started/installation/#install-on-kubernetes will need to be made.

**Comment by tilleryd** [comment]
Here's the doc story https://app.shortcut.com/grey-matter/story/27622/rename-ssh-private-key-in-install-guide.

**Comment by alecholmez** [comment]
@tilleryd this is to match sync. The whole conversation spawned out of confusion from having different file names. I'll update the description.

**Review by danielpcox — APPROVED** [review]
Seems fine, and I say we do this sooner rather than later so we can fix anything that breaks, but do we want to update the docs first?

**Pull request merged**
