### PR TITLE
add dashboard env vars for multi-mesh connections

### PR DESCRIPTION
**Pull request by tilleryd**

### CODE REVIEW

**Review by apatel4710 — COMMENTED** [review]
I checked the values of the newly added env vars to what I have in my original gitops-core and out of the 5 the only differing one is KEYCLOAK_AUTH_URL. The value I have is:

> "\(defaults.edge.oidc.endpoint)/auth/realms/(defaults.edge.oidc.realm)/protocol/openid-connect/token"}

I need to check if the current value still works or needs to be updated before I can approve

**Comment by tilleryd** [comment]
@apatel4710 I verified that that URL is available from Keycloak's `/auth/realms/realm/.well-known/openid-configuration` endpoint and update the env var.

**Comment by tilleryd** [comment]
@neagle Please review.

**Review by apatel4710 — APPROVED** [review]
All env vars match now and are accurate

**Pull request merged**
